# Linear Regression Multiple Variables

Below is the table containing home prices in monroe twp, NJ. Here price depends on area (square feet), bed rooms and age of the home (in years). Given these prices we have to predict prices of new homes based on area, bed rooms and age.

Given these home prices find out price of a home that has,

3000 sqr ft area, 3 bedrooms, 40 year old

2500 sqr ft area, 4 bedrooms, 5 year old

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [44]:
dataframe = pd.read_csv("homeprices.csv")
dataframe

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

data processing: chek for null values and fill them with appropriate values

In [45]:
dataframe.bedrooms = dataframe.bedrooms.fillna(dataframe.bedrooms.median())

In [46]:
dataframe

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

create linear regression object

In [47]:
reg = linear_model.LinearRegression()

call fit function and pass required parameters

In [48]:
reg.fit(dataframe[['area', 'bedrooms', 'age']], dataframe.price)

LinearRegression()

find the coeffient

In [49]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

find the intercept

In [50]:
reg.intercept_

221323.00186540408

find home price for 3000 sqrt area, 3 bedrooms, 40 yrs old

In [51]:
reg.predict([[3000, 3, 40]])

C:\Users\venka\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

equation to predict home price is

y = m1 * x1 +m *x2 + m * x3 + b

where y = value to be predicted
m = co-efficient
x = independent values (features)
b = inercept

so the equation become

price = m * area + m * bedrooms + m * age + b

In [52]:
112.06244194*3000+23388.88007794*3+(-3231.71790863)*40+221323.00186540408

498408.2515740241

find home price for 2500 sqrt area, 4 bedrooms, 5 yrs old

In [53]:
reg.predict([[2500,4,5]])

C:\Users\venka\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [54]:
112.06244194*2500+23388.88007794*4+(-3231.71790863)*5+221323.00186540408

578876.0374840142